# Generated by Django 5.0.2 on 2024-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
