# Generated by Django 5.0.2 on 2024-03-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tareas_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='available',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
