# Generated by Django 5.0.2 on 2024-03-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tareas_available_alter_tareas_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='available',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
