# Generated by Django 5.0.2 on 2024-03-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_tareas_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
