# Generated by Django 5.0.2 on 2024-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_tareas_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
